# Chapter 6 - Decision Tree Model

## Project: Credit Risk Score.

In [5]:
# Importing Python Packages. 

# Data Manipulation. 
import pandas as pd 
import numpy as np

# Data Visualization Packages. 
import seaborn as sns 
import matplotlib.pyplot as plt

# Data Gathering Package. 
import wget 

# Data preparation packages.
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction import DictVectorizer

# Model Training Packages.
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import roc_auc_score

# Other
from IPython.display import display 
%matplotlib inline

## Data Gathering.

In [2]:
# Data url link
url = 'https://github.com/gastonstat/CreditScoring/raw/master/CreditScoring.csv'

# Downloading data with wget.
# wget.download(url, 'data/credit_scoring.csv')

In [3]:
# Loading dataset.
credit_score = pd.read_csv('data/credit_scoring.csv')

# Viewing 
credit_score.head()

Status  Seniority  Home  Time  Age  Marital  Records  Job  Expenses  \
0       1          9     1    60   30        2        1    3        73   
1       1         17     1    60   58        3        1    1        48   
2       2         10     2    36   46        2        2    3        90   
3       1          0     1    60   24        1        1    1        63   
4       1          0     1    36   26        1        1    1        46   

   Income  Assets  Debt  Amount  Price  
0     129       0     0     800    846  
1     131       0     0    1000   1658  
2     200    3000     0    2000   2985  
3     182    2500     0     900   1325  
4     107       0     0     310    910

## Data Cleaning & Preparation. 

In [4]:
# Changing header to small cap.
credit_score.columns = credit_score.columns.str.replace(' ', '_').str.lower()

# Checking data columns names.
credit_score.columns

Index(['status', 'seniority', 'home', 'time', 'age', 'marital', 'records',
       'job', 'expenses', 'income', 'assets', 'debt', 'amount', 'price'],
      dtype='object')

In [5]:
credit_score.status.value_counts()

1    3200
2    1254
0       1
Name: status, dtype: int64

In [6]:
# Replacing numbers with values.
status_values = {
    1: 'ok',
    2: 'default',
    0: 'unk'
}

credit_score.status = credit_score.status.map(status_values)

# Check header. 
credit_score.head()

status  seniority  home  time  age  marital  records  job  expenses  \
0       ok          9     1    60   30        2        1    3        73   
1       ok         17     1    60   58        3        1    1        48   
2  default         10     2    36   46        2        2    3        90   
3       ok          0     1    60   24        1        1    1        63   
4       ok          0     1    36   26        1        1    1        46   

   income  assets  debt  amount  price  
0     129       0     0     800    846  
1     131       0     0    1000   1658  
2     200    3000     0    2000   2985  
3     182    2500     0     900   1325  
4     107       0     0     310    910

In [7]:
# Converting Values to str values. 
home_values = {
    1: 'rent',
    2: 'owner',
    3: 'private',
    4: 'ignorfe',
    5: 'parents',
    6: 'other',
    0: 'unk'
}

credit_score.home = credit_score.home.map(home_values)

marital_values = {
    1: 'single',
    2: 'married',
    3: 'widow',
    4: 'separated',
    5: 'divorced',
    0: 'unk'
}

credit_score.marital = credit_score.marital.map(marital_values)

records_values = {
    1: 'no',
    2: 'yes',
    0: 'unk'
}

credit_score.records = credit_score.records.map(records_values)

job_values = {
    1: 'fixed',
    2: 'partime',
    3: 'freelance',
    4: 'others',
    0: 'unk'
}

credit_score.job = credit_score.job.map(job_values)

In [8]:
# Checking result.
credit_score.head()

status  seniority   home  time  age  marital records        job  expenses  \
0       ok          9   rent    60   30  married      no  freelance        73   
1       ok         17   rent    60   58    widow      no      fixed        48   
2  default         10  owner    36   46  married     yes  freelance        90   
3       ok          0   rent    60   24   single      no      fixed        63   
4       ok          0   rent    36   26   single      no      fixed        46   

   income  assets  debt  amount  price  
0     129       0     0     800    846  
1     131       0     0    1000   1658  
2     200    3000     0    2000   2985  
3     182    2500     0     900   1325  
4     107       0     0     310    910

In [9]:
# Statistic overview.
credit_score.describe()

seniority         time          age     expenses        income  \
count  4455.000000  4455.000000  4455.000000  4455.000000  4.455000e+03   
mean      7.987205    46.441751    37.077666    55.568799  7.633170e+05   
std       8.173444    14.655225    10.984856    19.515878  8.703625e+06   
min       0.000000     6.000000    18.000000    35.000000  0.000000e+00   
25%       2.000000    36.000000    28.000000    35.000000  8.000000e+01   
50%       5.000000    48.000000    36.000000    51.000000  1.200000e+02   
75%      12.000000    60.000000    45.000000    72.000000  1.660000e+02   
max      48.000000    72.000000    68.000000   180.000000  1.000000e+08   

             assets          debt       amount         price  
count  4.455000e+03  4.455000e+03  4455.000000   4455.000000  
mean   1.060341e+06  4.043820e+05  1039.021773   1462.875645  
std    1.021757e+07  6.344253e+06   474.543007    628.089913  
min    0.000000e+00  0.000000e+00   100.000000    105.000000  
25%    0.000000e+00  0.000000e+00   700.000000   1117.500000  
50%    3.500000e+03  0.000000e+00  1000.000000   1400.000000  
75%    6.000000e+03  0.000000e+00  1300.000000   1692.000000  
max    1.000000e+08  1.000000e+08  5000.000000  11140.000000

In [10]:
# Removing Outlier with None. 

# Removing outliers for Debt column. 
credit_score.debt.replace(99999999, np.nan, inplace = True)

# Removing outlier for assets column.
credit_score.assets.replace(99999999, np.nan, inplace = True)

# Removing outlier for income column.
credit_score.income.replace(99999999, np.nan, inplace = True)

# Veiwing changes. 
credit_score[['income', 'debt', 'assets']].max()

income       959.0
debt       30000.0
assets    300000.0
dtype: float64

In [27]:
# Remove rows with unknow status.
credit_score = credit_score[credit_score.status != 'unk']

# Show result.
credit_score.status.value_counts(normalize = True)

ok         0.718455
default    0.281545
Name: status, dtype: float64

In [17]:
# Splitting dataset. 
# Full_Train & Test Dataset.
credit_train_full, credit_test = train_test_split(credit_score, test_size= 0.2, random_state = 10)

# Train & Validation Dataset.
credit_train, credit_val = train_test_split(credit_train_full, test_size = 0.25, random_state = 10)

# Reset index values. 
credit_train_full = credit_train_full.reset_index(drop=True)
credit_test = credit_test.reset_index(drop = True)
credit_train = credit_train.reset_index(drop = True)
credit_val = credit_val.reset_index(drop = True)

# Extract Dependent feature.
y_train = (credit_train['status']== 'ok').astype(int).values
y_test = (credit_test['status'] == 'ok').astype(int).values
y_val = (credit_val['status'] == 'ok').astype(int).values

# Delete dependent columns from dataset. 
del credit_train['status']
del credit_test['status']
del credit_val['status']

# Show all dataset. 
display(credit_train)
display(credit_test)
display(credit_val)

seniority   home  time  age  marital records        job  expenses  \
0            32  owner    36   56  married      no      fixed        60   
1            11   rent    60   38  married      no      fixed        82   
2             8   rent    36   36  married      no      fixed        78   
3             3  owner    48   26   single      no      fixed        35   
4             0  owner    18   20   single      no    partime        35   
...         ...    ...   ...  ...      ...     ...        ...       ...   
2668          1   rent    36   47  married     yes  freelance       105   
2669          2  owner    60   23  married      no      fixed        45   
2670          6  owner    48   33  married      no  freelance        45   
2671          8  owner    24   33  married      no      fixed        75   
2672          6  owner    60   28  married      no  freelance        60   

      income  assets    debt  amount  price  
0      152.0  7000.0     0.0    1000   2950  
1       71.0     0.0     0.0     900    977  
2      179.0     0.0     0.0     900   1503  
3      157.0  7000.0     0.0    1200   2053  
4      180.0  4000.0     0.0     700    960  
...      ...     ...     ...     ...    ...  
2668     0.0     0.0     0.0     500    500  
2669    78.0  5000.0  6300.0    1075   1123  
2670    78.0  3500.0     0.0    1100   1526  
2671   315.0  4500.0     0.0     400   1780  
2672   125.0     0.0     0.0     800   1700  

[2673 rows x 13 columns]

seniority     home  time  age   marital records        job  expenses  \
0            3  parents    18   42   married      no  freelance        75   
1            3  parents    60   30    single      no      fixed        35   
2            1  parents    60   36   married      no    partime        60   
3            1    other    36   28    single      no  freelance        35   
4           30    owner    24   57   married      no  freelance        45   
..         ...      ...   ...  ...       ...     ...        ...       ...   
886         15    owner    60   32  divorced      no  freelance        35   
887          3  parents    24   25    single     yes      fixed        35   
888          0    owner    48   44   married      no    partime        75   
889          6     rent    24   28   married      no      fixed        62   
890         14    owner    60   43   married      no      fixed        60   

     income   assets    debt  amount  price  
0     276.0   1500.0     0.0     750   1758  
1      86.0      0.0     0.0     750    829  
2      60.0      0.0     0.0    1400   1612  
3     100.0      0.0     0.0    1950   2074  
4      40.0  17000.0     0.0     400    500  
..      ...      ...     ...     ...    ...  
886     0.0   6000.0  3300.0    1550   1612  
887   128.0      0.0     0.0     300   1397  
888   120.0   4000.0     0.0     900   1204  
889   166.0      0.0     0.0     500   1150  
890   120.0   5000.0     0.0    1250   1557  

[891 rows x 13 columns]

seniority     home  time  age  marital records      job  expenses  \
0            0  parents    60   23   single      no  partime        35   
1            0    owner    60   30  married     yes    fixed        75   
2           25     rent    60   52  married      no    fixed        73   
3           22    other    24   36  married      no    fixed        45   
4           18    owner    48   32  married      no    fixed        75   
..         ...      ...   ...  ...      ...     ...      ...       ...   
886          7  parents    60   33   single      no  partime        35   
887          8    owner    36   53  married      no    fixed        45   
888          3  parents    60   39  married      no    fixed        45   
889          1  parents    24   29   single      no  partime        35   
890          0    other    60   38  married     yes    fixed        45   

     income  assets  debt  amount  price  
0     205.0     0.0   0.0    1400   1426  
1     255.0  4000.0   0.0    1500   1749  
2     127.0     0.0   0.0    1030   1250  
3     176.0     0.0   0.0     700   1428  
4      71.0  4000.0  39.0     660   1461  
..      ...     ...   ...     ...    ...  
886    70.0     0.0   0.0    1300   1438  
887   254.0  6000.0   0.0     350    575  
888    77.0     0.0   0.0    1000   1094  
889   147.0     0.0   0.0     650   1370  
890     0.0     0.0   0.0    1500   1700  

[891 rows x 13 columns]

## Training Model: Decision Tree.

In [30]:
# Converting data to dict.
train_dict = credit_train.to_dict(orient = 'records')

# Check result.
train_dict

[{'seniority': 32,
  'home': 'owner',
  'time': 36,
  'age': 56,
  'marital': 'married',
  'records': 'no',
  'job': 'fixed',
  'expenses': 60,
  'income': 152.0,
  'assets': 7000.0,
  'debt': 0.0,
  'amount': 1000,
  'price': 2950},
 {'seniority': 11,
  'home': 'rent',
  'time': 60,
  'age': 38,
  'marital': 'married',
  'records': 'no',
  'job': 'fixed',
  'expenses': 82,
  'income': 71.0,
  'assets': 0.0,
  'debt': 0.0,
  'amount': 900,
  'price': 977},
 {'seniority': 8,
  'home': 'rent',
  'time': 36,
  'age': 36,
  'marital': 'married',
  'records': 'no',
  'job': 'fixed',
  'expenses': 78,
  'income': 179.0,
  'assets': 0.0,
  'debt': 0.0,
  'amount': 900,
  'price': 1503},
 {'seniority': 3,
  'home': 'owner',
  'time': 48,
  'age': 26,
  'marital': 'single',
  'records': 'no',
  'job': 'fixed',
  'expenses': 35,
  'income': 157.0,
  'assets': 7000.0,
  'debt': 0.0,
  'amount': 1200,
  'price': 2053},
 {'seniority': 0,
  'home': 'owner',
  'time': 18,
  'age': 20,
  'marital': 's

In [33]:
# Creating Dict Vectorizer instance.
dv = DictVectorizer(sparse = False)

# Training and transforming data
x_train = dv.fit_transform(train_dict)

# Show result 
print(x_train, '\n')

# Show feature names. 
print(dv.get_feature_names())


[[5.6e+01 1.0e+03 7.0e+03 ... 0.0e+00 3.2e+01 3.6e+01]
 [3.8e+01 9.0e+02 0.0e+00 ... 0.0e+00 1.1e+01 6.0e+01]
 [3.6e+01 9.0e+02 0.0e+00 ... 0.0e+00 8.0e+00 3.6e+01]
 ...
 [3.3e+01 1.1e+03 3.5e+03 ... 0.0e+00 6.0e+00 4.8e+01]
 [3.3e+01 4.0e+02 4.5e+03 ... 0.0e+00 8.0e+00 2.4e+01]
 [2.8e+01 8.0e+02 0.0e+00 ... 0.0e+00 6.0e+00 6.0e+01]] 

['age', 'amount', 'assets', 'debt', 'expenses', 'home=ignorfe', 'home=other', 'home=owner', 'home=parents', 'home=private', 'home=rent', 'home=unk', 'income', 'job=fixed', 'job=freelance', 'job=others', 'job=partime', 'job=unk', 'marital=divorced', 'marital=married', 'marital=separated', 'marital=single', 'marital=unk', 'marital=widow', 'price', 'records=no', 'records=yes', 'seniority', 'time']


In [4]:
# Training Decision Tree model. 
dtm = DecisionTreeClassifier(max_depth = 3)

# Train model with training dataset. 
dtm.fit(x_train, y_train)

NameError: name 'x_train' is not defined