In [1]:
# Import packages 
import numpy as np
import pandas as pd
import wget

In [2]:
# downloading dataset using wget
url = "https://raw.githubusercontent.com/alexeygrigorev/mlbookcamp-code/master/chapter-02-car-price/data.csv"

response = wget.download(url, "car_price.csv")

100% [..........................................................................] 1475504 / 1475504

In [3]:
# load dataset 
car_price = pd.read_csv('car_price.csv')

car_price.head()

Make       Model  Year             Engine Fuel Type  Engine HP  \
0  BMW  1 Series M  2011  premium unleaded (required)      335.0   
1  BMW    1 Series  2011  premium unleaded (required)      300.0   
2  BMW    1 Series  2011  premium unleaded (required)      300.0   
3  BMW    1 Series  2011  premium unleaded (required)      230.0   
4  BMW    1 Series  2011  premium unleaded (required)      230.0   

   Engine Cylinders Transmission Type     Driven_Wheels  Number of Doors  \
0               6.0            MANUAL  rear wheel drive              2.0   
1               6.0            MANUAL  rear wheel drive              2.0   
2               6.0            MANUAL  rear wheel drive              2.0   
3               6.0            MANUAL  rear wheel drive              2.0   
4               6.0            MANUAL  rear wheel drive              2.0   

                         Market Category Vehicle Size Vehicle Style  \
0  Factory Tuner,Luxury,High-Performance      Compact         Coupe   
1                     Luxury,Performance      Compact   Convertible   
2                Luxury,High-Performance      Compact         Coupe   
3                     Luxury,Performance      Compact         Coupe   
4                                 Luxury      Compact   Convertible   

   highway MPG  city mpg  Popularity   MSRP  
0           26        19        3916  46135  
1           28        19        3916  40650  
2           28        20        3916  36350  
3           28        18        3916  29450  
4           28        18        3916  34500

## Question 1: What's the version of NumPy that you installed?


In [4]:
np.__version__

'1.23.1'

## Question 2: How many records are in the dataset?

In [5]:
# Check the data shape 
print(f"There are {car_price.shape[0]} rows and {car_price.shape[1]} columns in the car price dataset.")

There are 11914 rows and 16 columns in the car price dataset.


## Question 3: Who are the most frequent car manufacturers (top-3) according to the dataset?

In [6]:
# Getting the most Common car maker.
car_price.Make.value_counts()[0:3]

Chevrolet     1123
Ford           881
Volkswagen     809
Name: Make, dtype: int64

## Question 4: What's the number of unique Audi car models in the dataset?

In [7]:
car_price.query('Make == "Audi"')['Model'].nunique()

34

## Question 5: How many columns in the dataset have missing values?

In [8]:
# What is the number of columns with missing values
car_price.isna().any().sum()

5

## Question 6.1: Find the median value of "Engine Cylinders" column in the dataset. 

In [9]:
# Find the median of Engine Cylinders 
car_price['Engine Cylinders'].median()

6.0

## Question 6.2: calculate the most frequent value of the same "Engine Cylinders"

In [10]:
car_price['Engine Cylinders'].value_counts()

4.0     4752
6.0     4489
8.0     2031
12.0     230
5.0      225
10.0      68
0.0       56
3.0       30
16.0       3
Name: Engine Cylinders, dtype: int64

## Question 6.3: Use the fillna method to fill the missing values in "Engine Cylinders" with the most frequent value from the previous step.

In [11]:
# Checking to see if there is null value in the Engine Cylinders column
car_price['Engine Cylinders'].isna().sum()

30

In [12]:
# filling null value with most frequent.
car_price['Engine Cylinders'] = car_price['Engine Cylinders'].fillna(4.0)

In [13]:
# Checking for Null value
car_price['Engine Cylinders'].isna().sum()

0

## Question 6.4: calculate the median value of "Engine Cylinders" once again.

In [14]:
car_price['Engine Cylinders'].median()

6.0

## Question 7.1: Select all the "Lotus" cars from the dataset

In [15]:
# Selecting all the Lotus cars in the dataset.
lotus_car = car_price.query("Make == 'Lotus'")
lotus_car.head()

Make  Model  Year             Engine Fuel Type  Engine HP  \
3912  Lotus  Elise  2009  premium unleaded (required)      189.0   
3913  Lotus  Elise  2009  premium unleaded (required)      218.0   
3914  Lotus  Elise  2009  premium unleaded (required)      189.0   
3915  Lotus  Elise  2010  premium unleaded (required)      189.0   
3916  Lotus  Elise  2010  premium unleaded (required)      218.0   

      Engine Cylinders Transmission Type     Driven_Wheels  Number of Doors  \
3912               4.0            MANUAL  rear wheel drive              2.0   
3913               4.0            MANUAL  rear wheel drive              2.0   
3914               4.0            MANUAL  rear wheel drive              2.0   
3915               4.0            MANUAL  rear wheel drive              2.0   
3916               4.0            MANUAL  rear wheel drive              2.0   

              Market Category Vehicle Size Vehicle Style  highway MPG  \
3912  Exotic,High-Performance      Compact   Convertible           27   
3913  Exotic,High-Performance      Compact   Convertible           26   
3914  Exotic,High-Performance      Compact   Convertible           27   
3915  Exotic,High-Performance      Compact   Convertible           27   
3916  Exotic,High-Performance      Compact   Convertible           26   

      city mpg  Popularity   MSRP  
3912        21         613  43995  
3913        20         613  54990  
3914        21         613  47250  
3915        21         613  47250  
3916        20         613  54990

## Question 7.2: Select only columns "Engine HP", "Engine Cylinders".

In [16]:
# Selecting the columns Engine HP and Engine Cylinders
lotus_car = lotus_car[['Engine HP', 'Engine Cylinders']]
lotus_car.head()

Engine HP  Engine Cylinders
3912      189.0               4.0
3913      218.0               4.0
3914      189.0               4.0
3915      189.0               4.0
3916      218.0               4.0

## Question 7.3: Now drop all duplicated rows using drop_duplicates method

In [17]:
# Checking for dupilcated rows.
lotus_car.duplicated().sum()

20

In [18]:
# Dropping all duplicated rows 
lotus_car = lotus_car.drop_duplicates()

In [19]:
# Checking for any available duplicate in the data 
lotus_car.duplicated().sum()

0

## Question 7.4: Get the underlying NumPy array. Let's call it X.

In [20]:
# Checking the shape of the dataframe
lotus_car.shape

(9, 2)

In [21]:
# Getting lotus_car numpy arrays.
X = lotus_car.values
X

array([[189.,   4.],
       [218.,   4.],
       [217.,   4.],
       [350.,   8.],
       [400.,   6.],
       [276.,   6.],
       [345.,   6.],
       [257.,   4.],
       [240.,   4.]])

## Question 7.5: Compute matrix-matrix multiplication between the transpose of X and X.

In [22]:
# Multipling X with X transpose 
XTX = X.T.dot(X)
XTX.shape

(2, 2)

## Question 7.6: Invert XTX

In [23]:
# Get the inverse value of XTX 
XTX_inv = np.linalg.inv(XTX)
XTX_inv

array([[ 5.53084235e-05, -2.94319825e-03],
       [-2.94319825e-03,  1.60588447e-01]])

## Question 7.7: Create an array y

In [24]:
# Creating y array 
y = np.array([1100, 800, 750, 850, 1300, 1000, 1000, 1300, 800])
y

array([1100,  800,  750,  850, 1300, 1000, 1000, 1300,  800])

## Question 7.8: Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. 

In [25]:
# Multipling X and inverted XTX 
xtx_xt = XTX_inv.dot(X.T)

# Multipling xtx_xt with y 
w = xtx_xt.dot(y)

# What is the first value of the list.
w[0]

4.594944810094579